### ISSUE TITLE
Adding comments to SurfStat MATLAB functions

### ISSUE THREAD

**Issue by ReinderVosDeWael** [MICA-MNI/BrainStat#12]
SurfStat's in-line comments are a little lacking so lets fix that. Functions that have been ported from SurfStat to BrainStat are in matlab/surfstat_ported. Please PR the comments to my branch so we have a good overview of all comment additions before merging them to master.  

When you've added comments to a function, please list it here.

**Comment by sofievalk** [comment]
Hi, I had some more general comments and questions: 

- write and read volume, how needed are these? 
- SurfStatReadVol1 and SurfStatReadVol, bit challeging naming? 
- what are surface normals? (SurfStatWriteSurf1_nonorm)
- SurfStatWriteSurf1 > possibly we want to write it not to obj, but also mgh or gifti?
- SurfStatVol2Surf > is this still used? 
- SurfStatViews > did we want to keep this? 
- SurfStatViewData : changed?
- SurfStatT >> multivariate there is open end with  'Hotelling''s T for k>3
- SurfStatSurf2Vol, is nice but also difficult to use - not so useful (often)
- SurfStatStand >> did not even know this function existed !
- Is surfstatSmooth the same as FS smoothing? 
- SurfStatRoiLabel >> doesnt Brainspace already have a different function to align parcels 
to brain? 
- SurfStatRoi @boris we always did something different right? 
>> coordinate2surface might be useful function 
- Resels function >> old one better? Euler characteristic is used where?
- I guess we've been there, read vol / gifti and surface? 
- What about subcortical surfaces?

**Comment by sofievalk** [comment]
(I am half-way will do rest tomorrow)

**Comment by sheyma** [comment]
Hi, could somebody point me out please, where the most updated commentary for SurfStat-Matlab functions are?

**Comment by sofievalk** [comment]
Maybe in Reinder’s repo?

**Comment by sheyma** [comment]
Hi Sofie,
i cannot really find out where the new comments are added :(

**Comment by sheyma** [comment]
@ReinderVosDeWael : As far as I can see, there is no in-line commentary in matlab functions yet. If this is correct, maybe we can ask @sofievalk  and @MICA-MNI to give us a presentation about surfstat, then we can try to put nice comments by ourselves.

@sofievalk : is it OK for you, if I distribute your comments here into other issue lists, where they are maybe more relevant?
