### ISSUE TITLE
Update abagen integration

### ISSUE THREAD

**Issue by rmarkello** [MICA-MNI/BrainStat#137]
Since abagen v0.1 we natively support surface atlases, so there's no need to project surface parcellations to volumetric space before passing them through to `abagen.get_expression_data()`. I'd be happy to submit a PR to update the call out in `brainstat.context.genetics`, if you're interested, but wanted to know whether you'd like to integrate a deprecation period or just go ahead with it since you're still in alpha.

Specific tasks related to this update:

- [ ] Remove surface-to-volume projection from `brainstats.context.genetics` and pass surface parcellations (and geometry, if parcellations are not in the default/expected `fsaverage5` space) directly to `abagen`
- [ ] Add new and update old processing options (e.g., `exact` --> `missing`)
- [ ] Pin minimum version for `abagen` in requirements file

**Comment by ReinderVosDeWael** [comment]
Hi Ross,

It would be great if you could submit that as a PR. No need for a deprecation period - BrainStat is still early stage enough that I clearly tell anyone who starts using it that anything and everything is subject to change.
