### ISSUE TITLE
Replace `numpy_groupies.aggregate` with `np.bincount`

### ISSUE THREAD

**Issue by rmarkello** [MICA-MNI/BrainStat#138]
This is a relatively minor suggestion, but from what I can tell your use of `numpy_groupies` in `brainstat.mesh.data` could be replaced with `np.bincount`.

For example:

https://github.com/MICA-MNI/BrainStat/blob/f34ffa01274aabf411feb801a3ea1869f8a22d11/brainstat/mesh/data.py#L94

could be:

```python
agg_1 = np.bincount(edg[:, 0], minlength=(v + 1)) * 2
```

and

https://github.com/MICA-MNI/BrainStat/blob/f34ffa01274aabf411feb801a3ea1869f8a22d11/brainstat/mesh/data.py#L118

could be:

```python
agg_tmp1 = np.bincount(edg[:, 0], Yedg, minlength=(v + 1))[1:]
```

Since it seems this is the only location where `numpy_groupies` is used in the codebase it would remove the need to have it as a dependency (which is always nice!).

Happy to submit a quick PR for this, if there's interest.

**Comment by ReinderVosDeWael** [comment]
Hi Ross,

Yep - that sounds great. Would be great if you could submit that PR.
