### ISSUE TITLE
[ENH] Implement bigbrain context decoding

### ISSUE THREAD

**Issue by ReinderVosDeWael** [MICA-MNI/BrainStat#151]
Implement decoding of Casey's MPC maps. This would be very helpful to have done before OHBM.

**Comment by sheyma** [comment]
Could you please give some more details about Casey's MPC maps? What is it?

**Comment by ReinderVosDeWael** [comment]
c.f. https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000284

**Comment by sheyma** [comment]
Hi,
thanks for the link!
Nice paper reporting gradients of different modalities (histology, microstructural covariance and functional connectivity) + the meta-analytic decoding of their differences.

However, what I don't understand, why do we want to have this all in `brainstat`? 

Is it just to replicate [Paquola et al. 2019](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000284), ie with histological gradients with [plot_tutorial_02_context.py](https://github.com/MICA-MNI/BrainStat/blob/master/docs/python/tutorials/plot_tutorial_02_context.py):


![tutorial2figure](https://user-images.githubusercontent.com/2557416/121068039-0e2cb980-c7cc-11eb-9e9a-d720091a8f93.png)

Apparently, the whole effort requires:

[brainstat/context/histology.py](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/context/histology.py)
[test_histology.py](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/tests/test_histology.py)
[get_home_dir.m](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat_matlab/%2Bbrainstat_utils/get_home_dir.m)
[brainstat_matlab/context/histology/*](https://github.com/MICA-MNI/BrainStat/tree/master/brainstat_matlab/context/histology)
and so on.

Or, is the rationale actually to illustrate an example for the whole context decoding, and this module needs a set of reasonable data set, and you choose [Paquola et al. 2019](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000284) for this reason?

**Comment by ReinderVosDeWael** [comment]
Same reason as we use nimare and allen human brain atlas; contextual decoding of other data.

**Comment by ReinderVosDeWael** [comment]
Will close this issue as the PR is already implemented; can continue this on slack if you want.
