### ISSUE TITLE
add dataset fetcher 

### ISSUE THREAD

**Issue by PeerHerholz** [MICA-MNI/BrainStat#16]
A dataset fetcher could/should be added in order to prevent the necessity to include `image` files
in the repo and/or manually download them for running the tutorials and tests.

- [x] Generate list of files and/or datasets that should be fetchable
- [x] Store files and/or datasets at suitable place
- [x] Write fetcher
- [x] test fetcher

Should be supported by both, the MATLAB and the python version.

**Comment by PeerHerholz** [comment]
@ReinderVosDeWael, @OualidBenkarim, @MICA-MNI what dataset would use for this purpose and where would you store it? Both options, a private and a public repo would/should work.

**Comment by ReinderVosDeWael** [comment]
I'm not too familiar with public repositories for this, but there's always bic.box. 

Just to be sure, when you say a dataset fetcher, you mean something like this right https://github.com/MICA-MNI/BrainStat/blob/reinder_branch/matlab/multivariate/%2Bgenetics/%2Bapi/create_local_dataset.m .

**Comment by PeerHerholz** [comment]
Yes, exactly. 
Quick update: @ReinderVosDeWael, @OualidBenkarim and I talked about it and decided to go for the `BIC` option, utilizing/starting with the [surfstat tutorial dataset](https://github.com/MICA-MNI/micaopen/tree/master/surfstat/surfstat_tutorial), which will include `thickness` data in `fsaverage5` and a `.csv` with demographic information.

**Comment by MICA-MNI** [comment]
I think thats a splendid idea :)

**Comment by sheyma** [comment]
It would be great to run BrainStat with tutorial data!

Is there any progress on dataset fetcher already? Who wants to assign this ticket? I'd love to use it, if it is done.

**Comment by PeerHerholz** [comment]
Hi @sheyma,

I'll try my best to finish it tomorrow!

**Comment by sheyma** [comment]
@PeerHerholz : best notification received today! Thanks.

**Comment by PeerHerholz** [comment]
The download itself is working, but the data formatting and uncompressing is still very buggy. I will continue tomorrow. Sorry for the delay.

**Comment by PeerHerholz** [comment]
@sheyma, I have a working version and opened a PR over at #25.

**Comment by sheyma** [comment]
can we now close this issue? or, is there still stg to do with data fetcher?

**Comment by ReinderVosDeWael** [comment]
Lets keep it open as a reminder that I need to add the MATLAB equivalent.
