### ISSUE TITLE
add write output functionality

### ISSUE THREAD

**Issue by PeerHerholz** [MICA-MNI/BrainStat#19]
The toolbox should have functionality to export results to different file formats to enable further analyses, visualization, etc. in other software. More precisely this includes [GIFTI](https://www.nitrc.org/projects/gifti) and [CIFTI](https://www.nitrc.org/projects/cifti/). This could be an extra `function` and/or added to a `class`. 

- [ ] discuss if it should be `function` or `class` argument or both
- [ ] implement and test

Tagging @OualidBenkarim for this [nibabel](https://nipy.org/nibabel/) related adventure.

**Comment by ReinderVosDeWael** [comment]
Adding myself for the MATLAB side

**Comment by PeerHerholz** [comment]
Oh, sorry for missing the `MATLAB` gang @ReinderVosDeWael.

**Comment by PeerHerholz** [comment]
@OualidBenkarim the folks over at [niworkflows](https://github.com/nipreps/niworkflows) have some [cifti functions](https://github.com/nipreps/niworkflows/blob/master/niworkflows/interfaces/cifti.py) we should check out.

**Comment by sofievalk** [comment]
Ha, this would also relate to context decoding.
