### ISSUE TITLE
Some cool future functions (not included in initial release)

### ISSUE THREAD

**Issue by MICA-MNI** [MICA-MNI/BrainStat#20]
A short wish list of potentially neat future features, feel free to add requests

- [ ] Hotelling's T2 for more than 3 dimensions. 
- [ ] Cerebellar surfaces 
- [ ] Subcortex

**Comment by PeerHerholz** [comment]
+1 re subcortex + follow up: how are we looking wrt ultra high field? With recent advantages regarding e.g. in-vivo brainstem acquisition, there is one or the other nucleus that would love to be analyzed using `BrainStat` I think.

**Comment by sofievalk** [comment]
Definitely! I guess the sky is the limit. Possibly.. on longer term, it would be nice to add some developer feature where different surfaces / templates can be constructed and uploaded (?)

**Comment by sofievalk** [comment]
Bayesian framework - might get hotter and hotter. For multi-site replication tests possibly quite realistic to add (looking at the R code I've used)

**Comment by sheyma** [comment]
- [ ] SurfStatEdg --> implementing "poly..." instead of "triangles" 
- [ ] SurfStatSmooth --> kernel to be a REAL gaussian?! (SLV)
- [ ]  TCFE + FDR at cluster level

**Comment by sofievalk** [comment]
- [ ] Model selection beyond SurfStatF (information criteria)
