### ISSUE TITLE
BrainStat p to q values

### ISSUE THREAD

**Issue by sheyma** [MICA-MNI/BrainStat#205]
Hi,

this is actually an issue reported by a lab member of us, comparing brainstat with R:

![brainstat_issue_p2q](https://user-images.githubusercontent.com/2557416/127741825-76cfe770-00b4-4a0c-acc3-789bf48d898a.png)

any help is appreciated!

CC: @giacomobignardi

**Comment by ReinderVosDeWael** [comment]
First of all, which BrainStat version is this? This code should error with the current version as slm_grad.t is not callable. 

Secondly, you're bypassing the SLM object and calling its private methods directly which isn't exactly intended usage. I'll make an issue out of prepending an underscore to these methods to `fdr`, `t_test`, and similar functions to emphasize that these are not intended for calling directly.  

Here's what's happening: the t-test computes values from a (one-sided) Student t-test or Hotelling T2 depending on the data. I assume your use-case computes a student t-test and as such your p-values will also be one-sided. The intended usage here is to use the fit method with the appropriate parameters i.e. something like:

```
slm_grad = SLM(model, phenotype, two_tailed=True, correction='fdr')
slm_grad.fit(HCP_grad_long)
t_grad = slm_grad.t
q_grad = slm_grad.Q
```
This should correctly perform a two-tailed test.

**Comment by sheyma** [comment]
Hi @ReinderVosDeWael ,

thanks a lot for the prompt reply!

is there a way to tag our lab member Giaco here somehow , so he could follow up on this:

https://github.com/giacomobignardi

**Comment by ReinderVosDeWael** [comment]
Nope - just gotta tell him to go to our Issues page.

**Comment by sheyma** [comment]
cc test: If I put a comment here, would @giacomobignardi be notified?

**Comment by giacomobignardi** [comment]
cc test: If I put I comment here, would @sheyma see my comment and get a notification?

**Comment by sofievalk** [comment]
I see it :p

Op ma 2 aug. 2021 om 13:00 schreef giacomobignardi ***@***.***

**Comment by ReinderVosDeWael** [comment]
@giacomobignardi does the above resolve your issue?

**Comment by giacomobignardi** [comment]
@ReinderVosDeWael 
Yes, it does! I double-checked both in Python and in R and, following your snippet of code:

`p_grad_r_twoTail = 2*pt(abs(t_grad), df, lower.tail = F)
q_grad_r_twoTail = p.adjust(method = "fdr",p_grad_r_twoTail)
all.equal(q_grad_r_twoTail,q_grad1) # they are very similar (difference in rounding up to the 3rd digit,  with mean realative dif  = to 0.005655164)`

Moreover, I checked, and in R I get identical results by fitting i lm models, with i equal to the number of parcels:

`lm_grad= c()
for(i in nparcel){
  lm_i  = lm(grad ~ cov + phenotype,data = HCP_grad)
  sumy_i = summary(lm_i)
  lm_grad = rbind(
    lm_grad,
    cbind(
      beta_r = sumy_i$coefficients[3],
      t_r = sumy_i$coefficients[9],
      p_r = sumy_i$coefficients[12],
      parcel = I
      )
      )
}
all.equal(lm_grad$t_r,t_grad1) # t values are the same!
lm_grad$q_r = p.adjust(method = "fdr",lm_grad$p_r)
all.equal(lm_grad$q_r,LM_out_par$q_grad1_r_twoTail) # they are very similar (difference in rounding up to the 3rd digit, with mean realative dif  = to 0.005655164)`

@ReinderVosDeWael and @sheyma  I consider my original issue to be solved, thanks a lot!
