### ISSUE TITLE
Homogenize multiple comparisons correction and expand functions in BrainStat 

### ISSUE THREAD

**Issue by MICA-MNI** [MICA-MNI/BrainStat#21]
something like 

function slm = BrainStat_multipleComp(slm, type, vargin)
switch type
  case 'no' 
       slm.P = 1 - tcdf(slm.t, slm.df)  
  case 'bonferroni' 
      slm.P = 1 - tcdf(slm.t, slm.df); 
      slm.P = slm.P * length(slm.t); 
      slm.P(slm.P>1) = 1; 
 case 'fdr' 
     q = SurfStatQ(slm, vargin) % can be replaced with contents of SurfStatQ 
     slm.P = q; 
case 'rft' 
   . ...
case 'tfce' 
....
otherwise 
...

end
slm.Ptype = type; 
etc

**Comment by ReinderVosDeWael** [comment]
Closing this as its part of the refactoring discussion.
