### ISSUE TITLE
"TypeError: string indices must be integers" doing tutorial_01

### ISSUE THREAD

**Issue by m-petersen** [MICA-MNI/BrainStat#260]
* **What is the current behavior?**
When reproducing https://brainstat.readthedocs.io/en/master/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py during model fitting I face an error I don't quite understand (TypeError: string indices must be integers).

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**.
I just copy-pasted the code from the documentation website. The upstream commands work as expected. Inputs to SLM() look fine to me.

* **What is the expected behavior?**
Reproduction of the tutorial results

* **Please tell us about your computing environment:**
Ubuntu 20.04 desktop. brainstat installed in a separate conda environment.

* **Other information**
```
from brainstat.stats.SLM import SLM

contrast_age = model.AGE_AT_SCAN
slm_age = SLM(
    model, contrast_age, surf="civet41k", mask=mask, correction=["fdr", "rft"]
)
slm_age.fit(thickness)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_34268/503961295.py in <module>
      5     model, contrast_age, surf="civet41k", mask=mask, correction=["fdr", "rft"]
      6 )
----> 7 slm_age.fit(thickness)

~/miniconda3/envs/brainstat/lib/python3.7/site-packages/brainstat/stats/SLM.py in fit(self, Y)
    126         else:
    127             Y_masked = Y.copy()
--> 128         self._linear_model(Y_masked)
    129         self._t_test()
    130         if self.mask is not None:

~/miniconda3/envs/brainstat/lib/python3.7/site-packages/brainstat/stats/_linear_model.py in _linear_model(self, Y)
     44 
     45     if self.surf is not None:
---> 46         self.resl, mesh_connections = _compute_resls(self, residuals)
     47         key = list(mesh_connections.keys())[0]
     48         setattr(self, key, mesh_connections[key])

~/miniconda3/envs/brainstat/lib/python3.7/site-packages/brainstat/stats/_linear_model.py in _compute_resls(self, Y)
    432     else:
    433         key = "tri" if "tri" in self.surf else "lat"
--> 434         mesh_connections = {key: self.surf[key]}
    435 
    436     edges = mesh_edges(self.surf, self.mask)

TypeError: string indices must be integers
```

Any help highly appreciated. I will try to reproduce the error in a different environment during the coming days. Thanks a lot in advance.

Cheers,
Marvin

**Comment by ReinderVosDeWael** [comment]
What version of BrainStat are you running? Try 

```
import brainstat
brainstat.__version__
```

**Comment by m-petersen** [comment]
Hi Reinder,

it's 0.2.8.

**Comment by ReinderVosDeWael** [comment]
Ah, that's the issue; string support for the surface was added in 0.3.0. The surface can now be provided both as a BSPolyData (surface) object or as a string containing a template name (e.g. "civet41k", "fsaverage5"). The latter will allow us to support some template specific functionalities that wouldn't be possible otherwise. 

You can either update to the most recent version or use the tutorial of 0.2.8 (still available at https://github.com/MICA-MNI/BrainStat/blob/v0.2.8/docs/python/generated_tutorials/plot_tutorial_01_basics.ipynb). In short, you'd change the SLM definition as follows:

```
pial_combined = fetch_template_surface("civet41k", join=True)
slm_age = SLM(model, contrast_age, surf=pial_combined, mask=mask, correction="rft")
```

Let me know if that helps.

**Comment by m-petersen** [comment]
Updating to the latest version fixed the issue. Thanks for your help!
