### ISSUE TITLE
ImageFileError: Cannot work out file type of ...pial_left.gii.gz"

### ISSUE THREAD

**Issue by YH2010** [MICA-MNI/BrainStat#286]
I want to get expression data based on destrieux atlas, but there is something wrong as follows:

**My code:**
`rom brainstat.context.genetics import surface_genetic_expression
from nilearn import datasets
import numpy as np
destrieux = datasets.fetch_atlas_surf_destrieux()
labels = np.hstack((destrieux['map_left'], destrieux['map_right']))
fsaverage = datasets.fetch_surf_fsaverage()
surfaces = (fsaverage['pial_left'], fsaverage['pial_right'])

expression = surface_genetic_expression(labels, surfaces, space='fsaverage')`

when running the codes of last line:

**the error pop out as follows:**
ImageFileError: Cannot work out file type of "D:\Program Files (x86)\anaconda3\envs\machinelearning\lib\site-packages\nilearn\datasets\data\fsaverage5\pial_left.gii.gz"

I check the files, both of them exist.

WIN10 OS

**Comment by ReinderVosDeWael** [comment]
Hi, 

Please try removing the file and downloading it anew; I suspect its corrupted.

**Comment by zihuaihuai** [comment]
outdated
