### ISSUE TITLE
Copying the SurfStat core to Python

### ISSUE THREAD

**Issue by ReinderVosDeWael** [MICA-MNI/BrainStat#3]
Let's start with these first few functions and add more to the list as we progress.

- [x] SurfStatEdge.py 

- [x] SurfStatT.py

- [x] SurfStatNorm.py

- [x] SurfStatStand.py 

- [x] SurfStatSmooth.py

- [x] SurfStatCoord2Ind.py 

- [x] SurfStatInd2Coord.py 

- [x] SurfStatF.py

- [x] stat_threshold.py

- [x] SurfStatResels.py 

- [x] SurfStatPeakClus.py

- [x] SurfStatLinMod.py 

- [x] SurfStatP.py 

- [x] SurfStatQ.py  

- [x] SurfStatAvSurf.py

- [x] SurfStatAvVol.py (Şeyma is on it...)

- **Read/Write functions** (SurfStatRead* SurfStatWrite*)

file formats to be read in: *mgh, *gifti, *FS, *nifti, 

- **Visualization functions** (SurfStatCol* SurfStatDataCursor* SurfStatView*)

**Comment by ReinderVosDeWael** [comment]
Converting the above functions will require and equivalent of the term/random classes. I've made a start with the term class in PR #11 . Will continue to convert the classes in that PR but I figured I could put it up so others can join in.

**Comment by sheyma** [comment]
Hi, 
I started converting SurfStatT into python now. SurfStatLinMod is half-ready (it waits for term and random functions).

**Comment by sofievalk** [comment]
Differentiate between:
- read surf
- read data
- read vol (reads volume templates and features)

**Comment by ReinderVosDeWael** [comment]
All SurfStat core functionality has been converted. Closing this.
