### ISSUE TITLE
Context decoding

### ISSUE THREAD

**Issue by sofievalk** [MICA-MNI/BrainStat#32]
Ha, decoding galore. 

- [ ] continuous vs peak decoding
- [ ] Genetic decoding
- [ ] Neurosynth decoding
- [ ] Anatomy toolbox 
- [ ] Gradients 
- [ ] MNI peaks
- [ ] Output Neurovault
- [ ] Spatial correlation 
- [ ] information on model that was run, effect sizes, orthogonality

**Comment by PeerHerholz** [comment]
[Neurosynth](https://github.com/neurosynth/neurosynth) is no longer actively development. Depending on the scope and precise intent, the follow-up package/resource [NiMARE](https://github.com/neurostuff/NiMARE) could be utilized.
