### ISSUE TITLE
downloaded template "is not a gzip file"

### ISSUE THREAD

**Issue by GerardYu** [MICA-MNI/BrainStat#344]
Hi there i got the following error:

`meta_analytic_decoder("fsaverage5",HCP_results_scaled)`
```
2023-05-16 17:29:51,473 - brainstat - INFO - Fetching Neurosynth feature files. This may take several minutes if you haven't downloaded them yet.
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152Lin\tpl-MNI152Lin_res-02_desc-brain_mask.nii.gz
328B [00:00, 321kB/s]

Error in py_call_impl(callable, dots$args, dots$keywords) :
nibabel.filebasedimages.ImageFileError: File C:\Users\the_c\.cache\templateflow\tpl-MNI152Lin\tpl-MNI152Lin_res-02_desc-brain_mask.nii.gz is not a gzip file
```

i realized the downloaded `tpl-MNI152Lin_res-02_desc-brain_mask.nii.gz` file is a zero byte file. So I manually downloaded the template from https://www.templateflow.org/archive/ , replaced the zero byte file and it worked

**Comment by zihuaihuai** [comment]
Right now the download link works again: https://templateflow.s3.amazonaws.com/tpl-MNI152Lin\tpl-MNI152Lin_res-02_desc-brain_mask.nii.gz.
