### ISSUE TITLE
How to calulate Cohen's d by BrainStat

### ISSUE THREAD

**Issue by qiruizhangqirui** [MICA-MNI/BrainStat#345]
Hi! 
Effect sizes have become increasingly important in recent research, especially since effect sizes for various diseases are also available in the ENIGMA toolbox. However, I found that Cohen's d are not provided in Surfstat or Brainstat. There is a slm.ef in Surfstat, but it doesn't seem to be Cohen's d.
I noticed that in Ke Xie's latest TLE gradient article Cohen's d is reported and claimed to have been calculated using BrainStat.
Is there any way I can calculate Cohen's d value manually from slm struct?
Thanks,
Qirui Zhang

**Comment by saratheriver** [comment]
Hello,

Please read here on how to compute Cohen's d effect sizes: https://statisticsbyjim.com/basics/cohens-d/. 

You simply need the means of each group and the pooled SD.

Hope this helps -
