### ISSUE TITLE
FDR

### ISSUE THREAD

**Issue by knutj** [MICA-MNI/BrainStat#348]
* **What are you trying to do?**
What is the q limit for fdr. Is it 5 %?
* **If you've tried running this with BrainSpace code already, how did you do so, and what went wrong?**
It works, but the documentation does not specify the rate of FDR.
* **Please tell us about your computing environment:**
  Python 3.11 and Matlab 2024a, Fedora 39
* **Other information**

**Comment by zihuaihuai** [comment]
There isn't a preset q-value limit for the FDR correction in the code. Instead, the q-values are computed during the fitting process and stored in the self.Q attribute of the SLM class instance. You can apply your own q-value threshold (e.g., 0.05 for 5%) after fitting the model to determine statistical significance.
