### ISSUE TITLE
mapping voxels/vertices/parcels to brain anatomy

### ISSUE THREAD

**Issue by lukasvo76** [MICA-MNI/BrainStat#350]
Hi BrainStat team,

Just discovered your toolbox, looks awesome, and nicely documented, thanks!

What is not clear to me from the docs/tutorials is how to input my own data correctly as a subject-by-region/voxel/parcel-by-variate matrix. In other words, how will BrainSpace know which region/parcel/voxel in the brain column x corresponds to?

I typically have volumetric data, so should I use the read_volume function? Could you maybe provide an example on how to load voxel-based first-level beta/con maps from multiple subjects?

Thanks a lot for your help!

Best wishes,

Lukas

**Comment by zihuaihuai** [comment]
In BrainStat, the analysis typically focuses on a single target variable, such as cortical thickness. The data is organized in a matrix where subjects are rows and regions are columns. As for plotting, this is handled within BrainSpace. I recommend referring to Tutorial 0 in the BrainSpace documentation for more details. You can find the tutorial at the following link: [BrainSpace Tutorial 0](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial0.html#sphx-glr-python-doc-auto-examples-plot-tutorial0-py).

**Comment by lukasvo76** [comment]
Thank you Enning!

Is there a Matlab version of tutorial 0 by any chance, as I am not a Python user?

Best wishes,

Lukas

**Comment by zihuaihuai** [comment]
Hi Luckas,

Here is the doc page of the brainSpace. There is a section of matlab tutorials. 
https://brainspace.readthedocs.io/en/latest/index.html

Best,
Enning

**Comment by lukasvo76** [comment]
Hi Enning,

Yes, I have seen those, but tutorial 0 "preparing your data...", which is the one I need to answer my question, is not available in the Matlab package, only in the Python package.

Also, does BrainStat work with volumetric data, or only surface?

Thanks,

Lukas
