### ISSUE TITLE
How to perform paired sample t-test with Standard Linear regression model (SLM)

### ISSUE THREAD

**Issue by YH2010** [MICA-MNI/BrainStat#353]
Dear developers and everyone, 

I have a batch of longitudinal follow-up data before and after treatment. I want to perform paired sample t-test. I want to know if  BrainStat could accomplish this? 

Look forward to your reply！Thank you very much!

Sincerely,
Yong

**Comment by zihuaihuai** [comment]
Yes, you can use SLM to account for the effect in both groups and also perform paired tests.
