### ISSUE TITLE
the fetch function of glasser parcellation on fsaverage5 

### ISSUE THREAD

**Issue by RomainViardLille** [MICA-MNI/BrainStat#356]
Hi everyone and thanks for the work :

I want to use glasser parcellation on fsaverage5 with brainstat version 0.4.2 but a message "Array shape is not valid."
I isolated the problem in teh few lines of code below : 

`pial_left, pial_right = fetch_template_surface("fsaverage5",layer="pial",join=False)
inflated_left, inflated_right = fetch_template_surface("fsaverage5",layer="inflated",join=False)
pial_combined = fetch_template_surface("fsaverage5", join=True)
mask = fetch_mask("fsaverage5")
glasser = fetch_parcellation("fsaverage5", "glasser", 360)

pial_left_fslr32k, pial_right_fslr32k = fetch_template_surface("fslr32k", join=False)
inflated_left_fslr32k,inflated_right_fslr32k = fetch_template_surface("fslr32k",layer="inflated", join=False)
pial_combined_fslr32k = fetch_template_surface("fslr32k", join=True)
mask_fslr32k = fetch_mask("fslr32k")
glasser_fslr32k = fetch_parcellation("fslr32k", "glasser", 360)

print(f"number of unique values in glasser fsaverage5 : {len(np.unique(glasser))},and in glasser fslr32k :{len(np.unique(glasser_fslr32k))}")
print(f"number of points in fslr32k corresponds with number of values  : {glasser_fslr32k.shape} {inflated_right_fslr32k.GetPoints().shape} {inflated_left_fslr32k.GetPoints().shape}")
print(f"number of points in fsaverage does not correspond with number of values  : {glasser.shape},{inflated_right.GetPoints().shape},{inflated_left.GetPoints().shape}")
`
OUTPUT :

number of unique values in glasser fsaverage5 : **32608**,and in glasser fslr32k :**361**
number of points in fslr32k corresponds with number of values  : (**64984**,) (**32492**, 3) (**32492**, 3)
number of points in fsaverage does not correspond with number of values  : (**42734**,),(**10242**, 3),(**10242**, 3)

ENRIONNEMENT
on a 64-bit Ubuntu Ubuntu 20.04.6 LTS, Jupyter notebook on VSCode 1.93.0 an dpython v3.11.5
  
Did i miss something, or did something wrong ? (it seems to me that code works perfectly before (at the beginning of the summer))

**Comment by zihuaihuai** [comment]
Hi, i have run your code on my machine i got the following numbers:
"number of unique values in glasser fsaverage5 : 361,and in glasser fslr32k :361
number of points in fslr32k corresponds with number of values : (64984,) (32492, 3) (32492, 3)
number of points in fsaverage does not correspond with number of values : (20484,),(10242, 3),(10242, 3)"

It seems like on my side the number is right. Cannot really reproduce your bug at my side.

**Comment by RomainViardLille** [comment]
Top deleting the cache was the solution ....I didn't know that this folder was the cache folder...A big thanks to you

**Comment by RomainViardLille** [comment]
delete the cache folder : /Users/xxxxxxx/brainstat_data/parcellation_data solved this issue ...congrats to the brainstat team
