### ISSUE TITLE
What kind of thickness files are used in tutorial?

### ISSUE THREAD

**Issue by JohannesWiesner** [MICA-MNI/BrainStat#365]
* **What are you trying to do?**

The tutorial uses `brainstat.tutorial.utils.fetch_mics_data` to download a `thickness` object. I wonder what kind of freesurfer output files where used to create this? Just concatenated  `lh.thickness/rh.thickness` files for each subject? Was smoothing applied to this data?

**Comment by zihuaihuai** [comment]
Hi,

Thanks for your question.
 
The thickness object retrieved by this function represents subject-by-vertex cortical thickness data mapped to the fsaverage5 template. In FreeSurfer, the cortical thickness of each subject is typically computed separately for the left hemisphere (lh.thickness) and the right hemisphere (rh.thickness). These files contain cortical thickness measurements for each vertex on the cortical surface of that hemisphere, derived from structural MRI scans.

However, as a statistical package, the order of the voxels doesn't matter as long as you can recall the mapping when interpreting the data. If you're looking to plot the data, you may need to align it with the preparation steps of other plotting tools, such as BrainSpace, to ensure consistency in visualization.

Hope this helps!
